### ISSUE TITLE
EmoComposer send nothing

### ISSUE THREAD

**Issue by graille** [Emotiv/community-sdk#185] opened 2017-03-29 00:27 UTC
Hi !

I've a problem with EmoComposer, I have succesfully connected my application to the EmoComposer interface with 
`IEE_EngineRemoteConnect("127.0.0.1", 1726);`

And the user is correctly detected by my application
So, I push "Auto reset" on EmoComposer and click on the "Send" button

But when I execute the rest of the script and test it with 
```
int result = IEE_DataUpdateHandle(userID, hData);
std::cout << result << " " << EDK_OK << std::endl;
if (result != EDK_OK)
	continue;
```

"result" is always equal to 1024, and never equal to EDK_OK (which is equal to 0)...
The script works fine with a real headset 

I don't understand :(

**Comment by Pitmairen** [comment] 2017-03-31 09:25
I think there are some issues if you use different versions of the EmoComposer and the sdk.  I am on MacOS and for me the EmoComposer does **not** work if I use it with the latest version of the SDK, but if I use the 3.3.3 version of the SDK the Composer works.

**Comment by Force01** [comment] 2017-04-01 18:21
With MacOS I had a similar issue. A temp fix I found to work was to remove the edk.framework that I got from the 3.4.0 release that I added to my Library >> Framework, and replaced it with the 3.3.3 release version. Not sure what the issue is with 3.4.0 ver. yet but hope it helps you :)

**Comment by tungntEmotiv** [comment] 2017-04-04 02:36
Hi @graille . 
From sdk library version 3.4 , License is required to access EEG and Performance Metric.  So you need a license to can use IEE_DataUpdateHandle() api.
We have introduced a new composer which is compatible with by Sdk 3.4 . Please pick up from below path [composer](https://github.com/Emotiv/community-sdk/tree/master/tools/XavierComposer/Win32)

**Comment by tungntEmotiv** [comment] 2017-04-18 02:21
Hi @graille 
If you dont have any question , i will close the issue.

**Closed by tungntEmotiv** 2017-04-18 02:21 UTC
